# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  whatsappechodocker:
    image: whatsappechodocker
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5160:5160
